# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Search and Notify
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOPICS: ${{ secrets.TOPICS }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install phdseeker bs4 urllib3 poetry
        poetry --version
        poetry config experimental.new-installer false
        poetry config virtualenvs.create false
        poetry install -vv
    - name: Find PhD positions...
      run: |
        # verbose mode, up to 10 pages, and with csv output
        # more about it: https://github.com/Aghababaei/PhD-Seeker
        phdseeker -k $TOPICS -v -o csv
    - name: Notify
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAILS: ${{ secrets.TO_EMAILS }}
      run: |
        echo "Work in progress!"
        psn --days 7 --country germany --send-email
